version: '3.8'

services:
  postgres:
    image: postgres:13.10
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram_network
    restart: always

  backend:
    image: credo7/kittygram_backend:latest
    container_name: backend
    volumes:
      - media:/app/media
      - backend_static:/app/collected_static
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - kittygram_network
    restart: always

  frontend:
    image: credo7/kittygram_frontend:latest
    container_name: frontend
    volumes:
      - frontend_static:/app/build
    depends_on:
      - backend
    networks:
      - kittygram_network
    restart: always

  gateway:
    image: credo7/kittygram_gateway:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - frontend_static:/static
      - backend_static:/backend
      - media:/media
    depends_on:
      - backend
      - frontend
    networks:
      - kittygram_network
    restart: always

volumes:
  frontend_static:
  backend_static:
  media:
  pg_data:

networks:
  kittygram_network:
    driver: bridge
