version: '3.9'

services:
  frontend:
    image: credo7/kittygram_frontend:latest
    container_name: kittygram_frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
    env_file: .env
    volumes:
      - static:/app/static
    networks:
      - kittygram_network

  backend:
    image: credo7/kittygram_backend:latest
    container_name: kittygram_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    networks:
      - kittygram_network

  gateway:
    image: credo7/kittygram_gateway:latest
    container_name: kittygram_gateway
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - static:/app/static
      - media:/app/media
    networks:
      - kittygram_network

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram_network

networks:
  kittygram_network:
    driver: bridge

volumes:
  static:
  media:
  pg_data:
