#cloud-config

users:
  - name: user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ466S6HQuQRL5+m54sj5VYV3HQdNiqO3QRuHmK7LYnX vitaly.credo@gmail.com

write_files:
  - content: |
      #!/bin/bash
      apt-get update
      apt-get install -y docker.io docker-compose
      usermod -aG docker user
    path: /root/vm_prep.sh
    permissions: "0740"

runcmd:
  - sleep 120
  - sudo -i
  - /root/vm_prep.sh
